### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lurquhar1221** [lurquhar1221/LunarComputing#3]
- [ ] Make GUI
- [ ] bind TileComputer to Lua runtime
- [ ] Create Lua GUI Backend
- [ ] Create OS for computers
- [ ] Networking Packets
- [ ] Lua APIs
- [ ] Implement actual lua io 
- [x] Terminal backend

**Comment by lurquhar1221** [comment]
Seperating.
